In [1]:
import tensorflow as tf

## Eager Execution

Eager execution is an experimental interface to TensorFlow that provides an imperative programming style (à la, Torch7, NumPy). When you enable eager execution, TensorFlow operations execute immediately; you do not execute a pre-constructed graph with `Session.run()`.

### Currently we're doing this... 

In [2]:
x = tf.placeholder(tf.float32, shape=[1, 1])
m = tf.matmul(x, x)

with tf.Session() as sess:
    print(sess.run(m, feed_dict={x: [[2.]]}))

[[ 4.]]


### Getting eager execution (warning! -- Don't try this stuff in your production systems!!)



In [3]:
#!pip install tf-nightly

### Fixed the above with the following (I hope!)

```shell
MacBook-Pro-2:~ tarrysingh$ sudo pip install tf-nightly
Password:
The directory '/Users/tarrysingh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/tarrysingh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tf-nightly
  Downloading tf_nightly-1.5.0.dev20171122-cp36-cp36m-macosx_10_11_x86_64.whl (42.4MB)
    100% |████████████████████████████████| 42.4MB 18kB/s 
Requirement already satisfied: enum34>=1.1.6 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting mock>=2.0.0 (from tf-nightly)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Requirement already satisfied: protobuf>=3.4.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting backports.weakref>=1.0rc1 (from tf-nightly)
  Downloading backports.weakref-1.0.post1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: tb-nightly<1.6.0a0,>=1.5.0a0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: wheel>=0.26 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting absl-py (from tf-nightly)
Collecting pbr>=0.11 (from mock>=2.0.0->tf-nightly)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 7.4MB/s 
Requirement already satisfied: setuptools in ./anaconda/lib/python3.6/site-packages (from protobuf>=3.4.0->tf-nightly)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: html5lib==0.9999999 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: futures>=3.1.1 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: bleach==1.5.0 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Installing collected packages: pbr, mock, backports.weakref, absl-py, tf-nightly
Successfully installed absl-py-0.1.5 backports.weakref-1.0.post1 mock-2.0.0 pbr-3.1.1 tf-nightly-1.5.0.dev20171122
```


In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [2]:
print(tf.__version__)

1.5.0-dev20171122


### We are playing with fire here. Version 1.5!!! 

In [3]:
tfe.enable_eager_execution()

In [4]:
# multiple 3 X 3 matrix
x = tf.matmul([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ],
              [
               [10, 11, 12],
               [13, 14, 15],
               [16, 17, 18],
              ])

In [5]:
# add one to each element using tf.add for broadcasting
y = tf.add(x, 1)

In [6]:
# Create a random random matrix of, say 6 by 4 matrix
z = tf.random_uniform([6, 4])

In [9]:
print(x) # without eager execution

Tensor("MatMul_1:0", shape=(3, 3), dtype=int32)


In [7]:
print(x) # with eager execution

tf.Tensor(
[[ 84  90  96]
 [201 216 231]
 [318 342 366]], shape=(3, 3), dtype=int32)


In [8]:
print(y) # with eager execution

tf.Tensor(
[[ 85  91  97]
 [202 217 232]
 [319 343 367]], shape=(3, 3), dtype=int32)


In [9]:
print(z) #with eager exec

tf.Tensor(
[[ 0.13902152  0.30357194  0.55132675  0.29358554]
 [ 0.61529016  0.69093883  0.00179088  0.44634724]
 [ 0.97679567  0.4461503   0.75236928  0.0593257 ]
 [ 0.77715838  0.91196513  0.49345231  0.98986089]
 [ 0.67009616  0.59602785  0.50252724  0.15992355]
 [ 0.0602212   0.45736706  0.70411134  0.56758451]], shape=(6, 4), dtype=float32)


### Cool huh!

What you see is that with eager execution enabled, these ops consume and return multi-dimensional arrays as `Tensor` objects pretty much like what you see in `Torch` or `Numpy ndarray` or other imperative constructs.

[**its experimental, so don't go about playing with it in production!**] there I said it again 😌

These operations can also be triggered via operator overloading of the `Tensor` object.

Col thing is that you can use the `+` instead of tf.add, `-` for tf.subtract etc.

In [10]:
a = (tf.ones([1], dtype=tf.float32) + 1) *2 - 1
print(a)

tf.Tensor([ 3.], shape=(1,), dtype=float32)


In [11]:
a # here you get more info about the numpy array

<tf.Tensor: id=20, shape=(1,), dtype=float32, numpy=array([ 3.], dtype=float32)>

### Coverting to and from Numpy

This operations converts python objects to `Tensor` objects and vice versa.

In [12]:
import numpy as np

In [13]:
x = tf.add(1, 1)                             # tf.Tensor with a value of 2
y = tf.add(np.array(1), np.array(1))         # tf.Tensor w a value of 2
z = np.multiply(x, y)                        # numpu.int64 with a value of 4
print(x)
print(y)
print(z)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
4


#### you can explicitly convert using...

`tf.constant` as you see next...

You can also call `numpy()` method of a `Tensor` object to obtain its Numpy `ndarray` value.

In [14]:
np_x = np.array(2., dtype=np.float32)
x = tf.constant(np_x)
py_y = 3.
y = tf.constant(py_y)

# add them up + 1

z = x + y + 1

print(z)
print(z.numpy())

tf.Tensor(6.0, shape=(), dtype=float32)
6.0


### CPU vs GPU acceleration and telling Eager Exec where to offload the computation

Easiest way to do this is to enclose your computation in ith a `tf.device('/gpu:0')` block. In case you have multiple GPUs, this function might come handy `tfe.num_gpus()`, that should return the number of GPUs you have on your cluster.

Here we multiply 1000 x 1000 matrices on a CPU:

In [15]:
import time

def measure(x):
  # The very first time a GPU is used by TensorFlow, it is initialized.
  # So exclude the first run from timing.
  tf.matmul(x, x)

  start = time.time()
  for i in range(10):
    tf.matmul(x, x)
  end = time.time()

  return "Took %s seconds to multiply a %s matrix by itself 10 times" % (end - start, x.shape)

# Run on CPU:
with tf.device("/cpu:0"):
  print("CPU: %s" % measure(tf.random_normal([1000, 1000])))

# If a GPU is available, run on GPU:
if tfe.num_gpus() > 0:
  with tf.device("/gpu:0"):
    print("GPU: %s" % measure(tf.random_normal([1000, 1000])))

CPU: Took 0.2379150390625 seconds to multiply a (1000, 1000) matrix by itself 10 times


In [16]:
# you can copy Tensors to different devices

x = tf.random_normal([10, 10])

x_gpu0 = x.gpu()
x_cpu = x.cpu()

_ = tf.matmul(x_cpu, x_cpu) # will run this operation on CPU
_ = tf.matmul(x_gpu0, x_gpu0)# will run on your first GPU device, you can chang it to gpu1, gpu2 if you have many

if tfe.num_gpus() > 1:
    x_gpu1 = c.gpu()
    _ = tf.matmul(x_gpu1, x_gpu1)  # will run on your second GPU

RuntimeError: Error copying tensor to device: GPU:0. GPU:0 unknown device.

#### BTW I get an error above 👆 since I don't have a GPU on my Mac 

##  Automatic Differentiation with Eager Execution

As per [Wikipedia](https://en.wikipedia.org/wiki/Automatic_differentiation):

In mathematics and computer algebra, automatic differentiation (AD), also called algorithmic differentiation or computational differentiation,[1][2] is a set of techniques to numerically evaluate the derivative of a function specified by a computer program. AD exploits the fact that every computer program, no matter how complicated, executes a sequence of elementary arithmetic operations (addition, subtraction, multiplication, division, etc.) and elementary functions (exp, log, sin, cos, etc.). By applying the chain rule repeatedly to these operations, derivatives of arbitrary order can be computed automatically, accurately to working precision, and using at most a small constant factor more arithmetic operations than the original program.

Automatic differentiation is not:
- Symbolic differentiation, nor
- Numerical differentiation (the method of finite differences).

These classical methods run into problems: symbolic differentiation leads to inefficient code (unless carefully done) and faces the difficulty of converting a computer program into a single expression, while numerical differentiation can introduce round-off errors in the discretization process and cancellation. Both classical methods have problems with calculating higher derivatives, where the complexity and errors increase. Finally, both classical methods are slow at computing the partial derivatives of a function with respect to many inputs, as is needed for gradient-based optimization algorithms. Automatic differentiation solves all of these problems, at the expense of introducing more software dependencies.

<img src="images/AutomaticDifferentiationNutshell.png">

**Automatic Differentiation** in TensorFlow is useful when implementing several deep learning algorithms. Eager Execution provides an autograd-like API for automatic differentiation, especially for functions such as these:

- `tfe.gradients_function(f)` : This returns a python function that computes the derivatives of the python function `f` w.r.t its arguments. `f` should return a scalr value. When invoeked this function returns a list of `Tensor` objects (an element for each argument of `f`)
- `tfe.value_and_gradients_function(f)` : Just like the above function this one returns , when invoked, the value of `f` in addition to the list of derivatives of `f` w.r.t its arguments.

Lets take a look how this works with an example:


In [17]:
def f(x):
    return tf.multiply(x, x)  # Or x * x
assert 9 == f(3.).numpy()

df = tfe.gradients_function(f)
assert 6 == df(3.)[0].numpy()

# Second order deriviative.
d2f = tfe.gradients_function(lambda x : df(x)[0])
assert 2 == d2f(3.)[0].numpy()

# Third order derivative.
d3f = tfe.gradients_function(lambda x : d2f(x)[0])
assert 0 == d3f(3.)[0].numpy()

AttributeError: 'NoneType' object has no attribute 'numpy'

#### Still don't know why the darn Nonetype error 

In [18]:
def prediction(input, weight, bias):
    return input * weight + bias

# A toy dataset of points around 3 * x + 2
NUM_EXAMPLES = 1000
training_inputs = tf.random_normal([NUM_EXAMPLES])
noise = tf.random_normal([NUM_EXAMPLES])
training_outputs = training_inputs * 3 + 2 + noise

# A loss function: Mean-squared error
def loss(weight, bias):
    error = prediction(training_inputs, weight, bias) - training_outputs
    return tf.reduce_mean(tf.square(error))

# Function that returns the the derivative of loss with respect to
# weight and bias
grad = tfe.gradients_function(loss)

# Train for 200 steps (starting from some random choice for W and B, on the same
# batch of data).
W = 5.
B = 10.
learning_rate = 0.01
print("Initial loss: %f" % loss(W, B).numpy())
for i in range(200):
  (dW, dB) = grad(W, B)
  W -= dW * learning_rate
  B -= dB * learning_rate
  if i % 20 == 0:
    print("Loss at step %d: %f" % (i, loss(W, B).numpy()))
print("Final loss: %f" % loss(W, B).numpy())
print("W, B = %f, %f" % (W.numpy(), B.numpy()))

Initial loss: 70.327377
Loss at step 0: 67.532112
Loss at step 20: 30.218769
Loss at step 40: 13.837612
Loss at step 60: 6.642962
Loss at step 80: 3.481600
Loss at step 100: 2.091797
Loss at step 120: 1.480482
Loss at step 140: 1.211435
Loss at step 160: 1.092952
Loss at step 180: 1.040738
Final loss: 1.018471
W, B = 3.042722, 2.121703


### Customizing gradients

One may want to define custom gradients for an operation, or for a function. This may be useful for multiple reasons, including providing a more efficient or more numerically stable gradient for a sequence of operations.

For example, consider the function log(1 + e^x), which commonly occurs in the computation of cross entropy and log likelihoods.

In [19]:
def log1pexp(x):
    return tf.log( 1 + tf.exp(x))
grad_log1pexp = tfe.gradients_function(log1pexp)

# works well at x = 0
assert 0.5 == float(grad_log1pexp(0.)[0])

# Returns a 'nan' at x = 100 due to numerical instability
import math
assert math.isnan(float(grad_log1pexp(100.)[0]))

#### With eager execution , define a custom gradient to simplify the gradient expression 

In [20]:
@tfe.custom_gradient
def log1pexp(x):
    e = tf.exp(x)
    def grad(dy):
        return dy * (1 - 1 / (1 + e))
    return tf.log(1 + e), grad
grad_log1pexp = tfe.gradients_function(log1pexp)

# when x = 0

assert 0.5 == float(grad_log1pexp(0.)[0])

# when x = 100, it works too

assert 1.0 == float(grad_log1pexp(100.)[0])

## Models : Building and Training

Your computation may have several parameters to be optimized. Encapsulating them into re-usable classe and objects makes the code easier to understand and follow as compared to writing several top level functions with many arguments.

Eager Execution encourages eagerly :) to use the Kersd-type "Layer" classes in `tf.layers` module. Furthermore, you might want to apply some more sophisticated techniques to compute parameter updates, such as those in `tf.train.Optimizer` implementations.

In the next section we will walk through using `Optimizer` and `Layer` APIs to build a trainable TensorFlow graphs in an **eager execution enabled** environment.


### Variables and Optimizers

`tfe.Variable` objects store mutable `Tensor` values that can be accesed during training, making automatic differentiation easy. Particularly, parameters of a model can be encapsulated in Python classes as variable!

`tfe.gradient_function(f)` introduced earlier computes the derivative of `f`, which becomes a bit clunky when `f` depends on a large number of trainable parameters.

`tfe.implicit_gradients` is an alternative function with some useful properties such as:

- it calculates the derivative of `f` w.r.t all the `tfe.Variable`'s used by `f`
- when the returned function is invoked, it returns a list of (gradient value, Variable object) tuples.

Representing model parameters as `Variable` objects, along the use of `tfe.implicit_gradients`, typically results in a better encapsulation. 

For instance, the linear regression model described above can be written in a class as following -->



In [39]:
class Model(object):
    def __init__(self):
        self.W = tfe.Variable(5., name='weight')
        self.B = tfe.Variable(10., name='bias')
        
    # Define predict function
    def predict(self, inputs):
        return inputs * self.W + self.B

In [40]:
# define loss function
def loss(model, inputs, targets):
    error = model.predict(inputs) - targets
    return tf.reduce_mean(tf.square(error))

# A baby dataset of points around 3*x + 2
NUM_EXAMPLES     = 1000
training_inputs  = tf.random_normal([NUM_EXAMPLES])
noise            = tf.random_normal([NUM_EXAMPLES])
training_outputs = training_inputs * 3 + 2 + noise

# Define a model
model = Model()
# Define Derivatives
grad = tfe.implicit_gradients(loss)
# Define a strategy for updating the variables based on the derivatives
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

# Traning the loop
print("Initial loss: %f" %
      loss(model, training_inputs, training_outputs).numpy())
for i in range(201):
    optimizer.apply_gradients(grad(model, training_inputs, training_outputs))
    if i % 20 == 0:
        print("Loss at step %d: %f" % (i, loss(model, training_inputs, training_outputs).numpy()))
# Final output
print("Final loss: %f"% loss(model, training_inputs, training_outputs). numpy())
print("W, B = %s, %s"% (model.W.numpy(), model.B.numpy()))

Initial loss: 69.881783
Loss at step 0: 67.122467
Loss at step 20: 30.204607
Loss at step 40: 13.911569
Loss at step 60: 6.715141
Loss at step 80: 3.534178
Loss at step 100: 2.127149
Loss at step 120: 1.504377
Loss at step 140: 1.228563
Loss at step 160: 1.106341
Loss at step 180: 1.052153
Loss at step 200: 1.028117
Final loss: 1.028117
W, B = 3.01984, 2.12771
